import pygame

GAME_TITLE = "Glowing Cafe"

WIN_WIDTH = 1280
WIN_HEIGHT = 720

FPS = 60

MUSIC_VOLUME = 1.0

PLAYER_START_WIDTH = WIN_WIDTH / 8
BLOB_START_HEIGHT = WIN_HEIGHT / 2 + WIN_HEIGHT / 4
DRIP_START_HEIGHT = WIN_HEIGHT / 2
RO_START_HEIGHT = WIN_HEIGHT / 2 - WIN_HEIGHT / 4
